name: Run Playwright Tests on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests and Generate Report
        run: |
          npm run practice-test --reporter=html
          echo "Test run complete"

      - name: Upload Playwright HTML Report
        uses: actions/upload-pages-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
