name: Playwright Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests and Generate Report
        run: |
          npm run ui-test
          echo "Test run complete"

      - name: Upload test results
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          name: Test Results
          path: allure-results
